---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      args:
        [
          "--dockerfile=/workspace/Dockerfile",
          "--context=dir://workspace",
          "--destination=hikariai/kaniko-demo:1.0.0",
        ]
      volumeMounts:
        - name: kaniko-secret
          mountPath: /secret
      env:
        - name: DOCKERHUB_REGISTRY_CREDENTIALS
          value: /secret/kaniko-secret.json
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
